# Generated by Django 5.2.11 on 2026-03-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('speed_tap', 'Speed Tap'), ('hand_eye', 'Hand Eye Sync'), ('color_match', 'Color Match'), ('advanced_combo', 'Advanced Combo'), ('focus_hold', 'Focus Hold'), ('random_target', 'Random Target'), ('left_right', 'Left Right'), ('multi_object', 'Multi Object Tracking'), ('number_sequence', 'Number Sequence'), ('peripheral_flash', 'Peripheral Flash')], max_length=50)),
                ('score', models.IntegerField()),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
