# Generated by Django 5.2.11 on 2026-03-01 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_difficulty', models.CharField(default='Easy', max_length=20)),
                ('adaptive_difficulty', models.BooleanField(default=True)),
                ('reaction_time', models.CharField(default='easy', max_length=20)),
                ('color_match', models.CharField(default='easy', max_length=20)),
                ('number_sequence', models.CharField(default='easy', max_length=20)),
                ('random_target', models.CharField(default='easy', max_length=20)),
                ('multi_object_tracking', models.CharField(default='easy', max_length=20)),
                ('focus_hold', models.CharField(default='easy', max_length=20)),
                ('peripheral_flash', models.CharField(default='easy', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='difficulty_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
