# Generated by Django 5.2.11 on 2026-03-02 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('sport_name', models.CharField(default='Other', max_length=100)),
                ('score', models.IntegerField()),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('average_reaction_time_ms', models.FloatField(default=0.0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_hits', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
