# Generated by Django 5.2.11 on 2026-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
